### ISSUE TITLE
Fix dirty vendor commit

### ISSUE THREAD

**Issue by tonyhb** [rsc/letsencrypt#18]
As commented here: https://github.com/rsc/letsencrypt/issues/15#issuecomment-246543640, this project contains an invalid/dirty vendor.

It states that it checks out ca19a90028e242e878585941c2a27c8f3b3efc25, though that commit doesn't actually contain the function TLSSNI01ChallengeCertDomain which this library uses.

See: https://github.com/xenolf/lego/blob/ca19a90028e242e878585941c2a27c8f3b3efc25/acme/tls_sni_challenge.go

vs the vendored:

https://github.com/rsc/letsencrypt/blob/master/vendor/github.com/xenolf/lego/acme/tls_sni_challenge.go#L44

**Comment by vikstrous** [comment]
Looks like this is fixed in https://github.com/rsc/letsencrypt/pull/12

**Comment by rsc** [comment]
I modified the code after vendoring it. The vendor.json file records the copy I started with. Any diffs are local modifications. That doesn't make it invalid.

**Comment by vikstrous** [comment]
In case anyone else runs into this: glide can help work around this with the following config:

```
- package: github.com/xenolf/lego
  repo: https://github.com/vikstrous/lego
  version: 8bb3dce0bea06e315bcbe18a5806ae0716514dfc
  subpackages:
  - acme
```
